<?php

namespace AppBundle\Repository;

/**
 * OccurenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccurenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findjobs($words){
        $qb= $this->createQueryBuilder('o');
        $qb->select('o.id');
        $i=0;
        $req = "";
        foreach($words as $word){
            if ($i > 0){
                $req.= " OR ";
            }
            $req.='w.tag'.'= :item'.$i.'';
            $qb->setParameter('item'.$i, $word);
            $i++;
        }
        $qb->join('o.word', 'w');
        $qb->where($req);
        return $qb->getQuery()->getResult();
    }
}
