<?php

namespace AppBundle\Repository;

/**
 * OccurenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccurenceRepository extends \Doctrine\ORM\EntityRepository
{
}
