app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Main:index }

autocomplete:
    path:     /autocomplete
    defaults: { _controller: AppBundle:Main:wordAutocomplete }

results:
    path:     /results
    defaults: { _controller: AppBundle:Main:results }