app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Main:index }

autocomplete:
    path:     /autocomplete
    defaults: { _controller: AppBundle:Main:wordAutocomplete }

result:
    path:     /result
    defaults: { _controller: AppBundle:Main:result }