AppBundle\Entity\Stat:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\StatRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        number:
            type: float
            nullable: true
        type:
            type: string
            length: 255
            unique: false
            nullable: true

    lifecycleCallbacks: {  }
