MigrationBundle\Entity\Interview:
    type: entity
    table: interview
    repositoryClass: MigrationBundle\Repository\InterviewRepository
    indexes:
        IDX_CF1D3C34A76ED395:
            columns:
                - user_id
        IDX_CF1D3C34BE04EA9:
            columns:
                - job_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        bonusWord:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: bonus_word
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        job:
            targetEntity: Job
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                job_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        answer:
            targetEntity: Answer
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: interview
            joinTable:
                name: interviews_answers
                joinColumns:
                    -
                        name: interview_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: answer_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
