MigrationBundle\Entity\User:
    type: entity
    table: user
    indexes:
        u_news:
            columns:
                - newsletter
        u_usrn:
            columns:
                - username
        u_usrn_c:
            columns:
                - username_canonical
        u_email_c:
            columns:
                - email_canonical
        u_email:
            columns:
                - email
    uniqueConstraints:
        UNIQ_8D93D64992FC23A8:
            columns:
                - username_canonical
        UNIQ_8D93D649A0D96FBF:
            columns:
                - email_canonical
        UNIQ_8D93D649C05FB297:
            columns:
                - confirmation_token
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        usernameCanonical:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
            column: username_canonical
        email:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        emailCanonical:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
            column: email_canonical
        enabled:
            type: boolean
            nullable: false
        salt:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        confirmationToken:
            type: string
            nullable: true
            length: 180
            options:
                fixed: false
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
            nullable: false
            length: null
            options:
                fixed: false
        firstname:
            type: string
            nullable: false
            length: 35
            options:
                fixed: false
        lastname:
            type: string
            nullable: false
            length: 35
            options:
                fixed: false
        gender:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        status:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        age:
            type: smallint
            nullable: false
            options:
                unsigned: false
        department:
            type: smallint
            nullable: false
            options:
                unsigned: false
        newsletter:
            type: boolean
            nullable: false
        satisfaction:
            type: smallint
            nullable: true
            options:
                unsigned: false
        comment:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
